services:
  - type: web
    name: forkfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 scripts/run.py
    healthCheckPath: /api/v1/health
    envVars:
      - key: SUPABASE_PASSWORD
        sync: false
      - key: OPEN_ROUTER_API_KEY
        sync: false
      - key: API_AUTH_TOKEN
        sync: false
